### ISSUE TITLE
pjax和相册加密有冲突

### ISSUE THREAD

**Issue by zhoubin-me** [YunYouJun/hexo-theme-yun#202]
开启pjax后，输入相册密码进不去
<!--

发现开启后相册地址会发生变化，后面多了点东西，可能跟这个有关。

**Comment by YunYouJun** [comment]
![image](https://user-images.githubusercontent.com/25154432/141262141-ae4056a6-1c25-4906-bfb6-e6246c1675dc.png)

https://yun.yunyoujun.cn/guide/page.html#%E7%9B%B8%E5%86%8C%E9%A1%B5

**Comment by zhoubin-me** [comment]
另外，本地调试时，密码只能输一次，页面刷新再输入密码就进不了了。deploy则没这个问题。

**Comment by YunYouJun** [comment]
见上文。主题层面无解。

**Comment by showmaker-hub** [comment]
你好，请问楼主解决了么

**Comment by YunYouJun** [comment]
> 你好，请问楼主解决了么

相册加密的 PJAX 是因为 Hexo 本地预览重新加密了一遍，部署后正常。这个实在没有办法解决。

**Comment by showmaker-hub** [comment]
那还剩那个aplayer的meting播放器那个，这个能解决么



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月10日(周五) 晚上9:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [YunYouJun/hexo-theme-yun] pjax和相册加密有冲突 (Issue #202)




  
你好，请问楼主解决了么
  
相册加密的 PJAX 是因为 Hexo 本地预览重新加密了一遍，部署后正常。这个实在没有办法解决。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YunYouJun** [comment]
> 那还剩那个aplayer的meting播放器那个，这个能解决么

是 https://github.com/YunYouJun/hexo-theme-yun/issues/195 吗？
